### PR TITLE
Add support for txt files

### PR DESCRIPTION
**Pull request by JKamsker**
Previously it wasnt able to convert .txt files

### CODE REVIEW

**Comment by armathor** [comment]
Shortly chipping in to confirm that uploading .txt with the old code is not working here on my side, too. Getting:

{'Error: Invalid file format. Please try again.'}

While uploading .docx works.

I'm new here btw. since yesterday.

Will try now if the suggested fix works, but looks good to me on first sight.

**Comment by armathor** [comment]
Ok, the solution works here.

But I'm a bit clueless about the following:

The original logic seems to send the attachment twice. At first within the upload_attachment function through:

response = requests.post(url, headers=headers, files=files)

and a second time a bit later within the send_message function through:

response = requests.post(url, headers=headers, data=payload, stream=True)

While the solution within this pull request omits the first sending, because it returns from the upload_attachment function before the first sending happens.

But nevertheless, the solution seems to work. This might be a hint that sending twice is not really necessary (or might be even the reason of this problem??). Though at this point of time I'm not understanding fully why, would have to analyze it further. So fyi.

But nice to have the txt thing working now. Because that's exactly what I need right now.

Thanks so far and best wishes!

**Comment by JKamsker** [comment]
@armathor I think upload attachment uploads the attachment and the send_message usually sends a reference to the uploaded attachment or the textual version of the file.

**Comment by armathor** [comment]
@JKamsker 

Maybe yes. Don't know though, would have to analyze closer to comment that. Am unfortunately a bit too busy atm to do that. Just wanted to give a hint.

But your version seems to work although you've omitted the first post request. 

Well, I definitely can live with that for now 🙂

**Comment by JKamsker** [comment]
@KoushikNavuluri Why was this closed?

**Comment by KoushikNavuluri** [comment]
Hey, @JKamsker Thanks for the check!
I've recently found a package which handles files easily , currently experimenting with it , and going to update the code with that package sooner.

**Comment by JKamsker** [comment]
@KoushikNavuluri https://github.com/KoushikNavuluri/Claude-API/blob/main/claude-api/claude_api.py#L232

Now that you have copied my code, it would be appreciated if you would credit me for it.

**Comment by KoushikNavuluri** [comment]
Hey , @JKamsker can't get you?

**Comment by JKamsker** [comment]
@KoushikNavuluri I noticed that you've taken inspiration from this PR and have incorporated the code manually. While this doesn't reflect on my profile's activity, I'm glad to see the code being used! 

Could you please add a section in your readme to acknowledge contributors, [similar to this](https://github.com/rosenbjerg/FFMpegCore#code-contributors)? It would be a great way to recognize everyone's efforts. Thank you!

**Pull request closed without merging**
